package aws.lambda.custom.runtime.integration;


import com.agorapulse.micronaut.agp.ApiGatewayProxyHandler;
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent;
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent;

import javax.inject.Inject;

/**
 * This class is likely to be autogenerated
 */
public class MicronautLambdaApplicationAdapter implements AwsLambdaApplicationAdapter {


    @Inject
    private ApiGatewayProxyHandler apiGatewayProxyHandler;

    @Override
    public APIGatewayProxyResponseEvent invoke(APIGatewayProxyRequestEvent event, AwsLambdaContext context) {
        return apiGatewayProxyHandler.handleRequest(event, context);
    }
}
